### PR TITLE
Subscript DSEL

### PR DESCRIPTION
**Pull request by brycelelbach**
Add direct multi-dimensional indexing calculations and a small DSEL for C-style multidimensional subscript syntax to DataArray; this will remove the need for pointer trees and will help down the line when we need to vectorize Tempest's kernels.

NOTE: Paul, merge in the makefile_rewrite pull request first, this one is branched off of that one.

### CODE REVIEW

**Comment by brycelelbach** [comment]
The last commit in this merge removes pointer trees entirely from the code. Yay!

**Comment by ghost** [comment]
Everyone,

I'm trying out the new code and my compilation breaks with the following:

mpiCC -L../../lib -L/opt/local/lib -llapack -lblas -o BaroclinicWaveJWTest
/home/jeguerra/Desktop/tempestmodel/test/nonhydro_sphere/build/BaroclinicWaveJWTest.o
-lhardcoreatm -ltempestbase -lnetcdf -lnetcdf_c++
../../lib/libhardcoreatm.a(JacobianFreeNewtonKrylov.o): In function
`JacobianFreeNewtonKrylov::PerformJFNK_NewtonStep(double*, int, double)':
JacobianFreeNewtonKrylov.cpp:(.text+0x18c8): undefined reference to`dnrm2_'
JacobianFreeNewtonKrylov.cpp:(.text+0x1a22): undefined reference to `dscal_'
JacobianFreeNewtonKrylov.cpp:(.text+0x1a6c): undefined reference to`dcopy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x1bb3): undefined reference to `daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x1d72): undefined reference to`ddot_'
JacobianFreeNewtonKrylov.cpp:(.text+0x1dfd): undefined reference to `daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x1e38): undefined reference to`dnrm2_'
JacobianFreeNewtonKrylov.cpp:(.text+0x1e8d): undefined reference to `dscal_'
JacobianFreeNewtonKrylov.cpp:(.text+0x1efa): undefined reference to`dcopy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x2176): undefined reference to `daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x21fa): undefined reference to`daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x2329): undefined reference to `dnrm2_'
JacobianFreeNewtonKrylov.cpp:(.text+0x2568): undefined reference to`daxpy_'
../../lib/libhardcoreatm.a(JacobianFreeNewtonKrylov.o): In function
`JacobianFreeNewtonKrylov::PerformBICGSTAB_NewtonStep(double*, int,
double)':
JacobianFreeNewtonKrylov.cpp:(.text+0x36e2): undefined reference to`dcopy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3789): undefined reference to `ddot_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3813): undefined reference to`daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3854): undefined reference to `dscal_'
JacobianFreeNewtonKrylov.cpp:(.text+0x38ab): undefined reference to`daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3913): undefined reference to `daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3a77): undefined reference to`ddot_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3b69): undefined reference to `dcopy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3bc6): undefined reference to`daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3c2e): undefined reference to `daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3d81): undefined reference to`ddot_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3dfc): undefined reference to `daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3e59): undefined reference to`daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3f3b): undefined reference to `dcopy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3f9d): undefined reference to`daxpy_'
JacobianFreeNewtonKrylov.cpp:(.text+0x3fe3): undefined reference to `ddot_'
JacobianFreeNewtonKrylov.cpp:(.text+0x40ef): undefined reference to`ddot_'
JacobianFreeNewtonKrylov.cpp:(.text+0x441f): undefined reference to `dcopy_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DGEMM(DataArray2D<double>&, DataArray2D<double>&,
DataArray2D<double>&, double, double)':
LinearAlgebra.cpp:(.text+0xf6): undefined reference to `dgemm_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DGESV(DataArray2D<double>&, DataArray1D<double>&,
DataArray1D<int>&)':
LinearAlgebra.cpp:(.text+0x1db): undefined reference to `dgesv_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DGESV(DataArray2D<double>&, DataArray2D<double>&,
DataArray1D<int>&)':
LinearAlgebra.cpp:(.text+0x2c8): undefined reference to `dgesv_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DGBSV(DataArray2D<double>&, DataArray1D<double>&,
DataArray1D<int>&, int, int)':
LinearAlgebra.cpp:(.text+0x3d7): undefined reference to `dgbsv_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DTPSV(char, char, char, int, DataArray1D<double>&,
DataArray1D<double>&)':
LinearAlgebra.cpp:(.text+0x472): undefined reference to `dtpsv_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DGETRF(DataArray2D<double>&, DataArray1D<int>&)':
LinearAlgebra.cpp:(.text+0x4e8): undefined reference to `dgetrf_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DGBTRF(DataArray2D<double>&, DataArray1D<int>&, int, int)':
LinearAlgebra.cpp:(.text+0x56e): undefined reference to `dgbtrf_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DGETRS(char, DataArray2D<double>&, DataArray1D<double>&,
DataArray1D<int>&)':
LinearAlgebra.cpp:(.text+0x615): undefined reference to `dgetrs_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DGBTRS(char, DataArray2D<double>&, DataArray1D<double>&,
DataArray1D<int>&, int, int)':
LinearAlgebra.cpp:(.text+0x6c9): undefined reference to `dgbtrs_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DGETRI(DataArray2D<double>&, DataArray1D<int>&,
DataArray1D<double>&)':
LinearAlgebra.cpp:(.text+0x755): undefined reference to `dgetri_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DTRTRI(char, char, DataArray2D<double>&)':
LinearAlgebra.cpp:(.text+0x88d): undefined reference to `dtrtri_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DGEQRF(DataArray2D<double>&, DataArray1D<double>&,
DataArray1D<double>&)':
LinearAlgebra.cpp:(.text+0x970): undefined reference to `dgeqrf_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::DORGQR(DataArray2D<double>&, DataArray1D<double>&,
DataArray1D<double>&)':
LinearAlgebra.cpp:(.text+0xa06): undefined reference to `dorgqr_'
../../lib/libtempestbase.a(LinearAlgebra.o): In function
`LAPACK::GeneralizedInverseSVD(DataArray2D<double>&, DataArray2D<double>&)':
LinearAlgebra.cpp:(.text+0x189e): undefined reference to `dgesvd_'
../../lib/libtempestbase.a(PolynomialInterp.o): In function
`PolynomialInterp::InterpolateCoeffs(int, double const_, double const_,
double_, double, double_, int*)':
PolynomialInterp.cpp:(.text+0xa9a): undefined reference to `dgesv_'

Most likely some missing packages on my end. I'll look for that. I'm
running Ubuntu locally so I can manage anything that is missing. Looks like
my LAPACK set is incomplete. I ran "make clean" and then "make all" like I
used to. Do I need a different compile sequence? Is there a configuration
file involved now? Thanks,

Jorge

On Fri, Feb 5, 2016 at 10:04 PM, Paul Ullrich notifications@github.com
wrote:

> Merged #3 https://github.com/paullric/tempestmodel/pull/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/paullric/tempestmodel/pull/3#event-541599844.

## 

Jorge E. Guerra
PhD Candidate, Atmospheric Science, LAWR
Hoagland 230, U.C. Davis

**Comment by paullric** [comment]
I suspect it's not detecting your system type and so is forgetting to -lblas (or however you link with LAPACK).  Try poking around in the mk directory.

~ Paul

**Comment by ghost** [comment]
Ok I see that things are very different now. Do I have to add to the
system.make? It is not very clear to me how the new compile sequence
executes. I have those libraries installed so the linking flags are there
but the compiler can't find them.

On Sat, Feb 6, 2016 at 12:11 PM, Paul Ullrich notifications@github.com
wrote:

> I suspect it's not detecting your system type and so is forgetting to
> -lblas (or however you link with LAPACK). Try poking around in the mk
> directory.
> 
> ~ Paul
> 
> > On Feb 6, 2016, at 11:59 AM, Jorge E Guerra notifications@github.com
> > wrote:
> > 
> > Everyone,
> > 
> > I'm trying out the new code and my compilation breaks with the following:
> > 
> > mpiCC -L../../lib -L/opt/local/lib -llapack -lblas -o
> > BaroclinicWaveJWTest
> > 
> > /home/jeguerra/Desktop/tempestmodel/test/nonhydro_sphere/build/BaroclinicWaveJWTest.o
> > -lhardcoreatm -ltempestbase -lnetcdf -lnetcdf_c++
> > ../../lib/libhardcoreatm.a(JacobianFreeNewtonKrylov.o): In function
> > `JacobianFreeNewtonKrylov::PerformJFNK_NewtonStep(double*, int, double)':
> > JacobianFreeNewtonKrylov.cpp:(.text+0x18c8): undefined reference to
> > `dnrm2_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x1a22): undefined reference to
> > `dscal_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x1a6c): undefined reference to
> > `dcopy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x1bb3): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x1d72): undefined reference to
> > `ddot_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x1dfd): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x1e38): undefined reference to
> > `dnrm2_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x1e8d): undefined reference to
> > `dscal_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x1efa): undefined reference to
> > `dcopy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x2176): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x21fa): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x2329): undefined reference to
> > `dnrm2_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x2568): undefined reference to
> > `daxpy_'
> > ../../lib/libhardcoreatm.a(JacobianFreeNewtonKrylov.o): In function
> > `JacobianFreeNewtonKrylov::PerformBICGSTAB_NewtonStep(double*, int,
> > double)':
> > JacobianFreeNewtonKrylov.cpp:(.text+0x36e2): undefined reference to
> > `dcopy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3789): undefined reference to
> > `ddot_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3813): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3854): undefined reference to
> > `dscal_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x38ab): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3913): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3a77): undefined reference to
> > `ddot_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3b69): undefined reference to
> > `dcopy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3bc6): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3c2e): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3d81): undefined reference to
> > `ddot_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3dfc): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3e59): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3f3b): undefined reference to
> > `dcopy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3f9d): undefined reference to
> > `daxpy_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x3fe3): undefined reference to
> > `ddot_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x40ef): undefined reference to
> > `ddot_'
> > JacobianFreeNewtonKrylov.cpp:(.text+0x441f): undefined reference to
> > `dcopy_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DGEMM(DataArray2D<double>&, DataArray2D<double>&,
> > DataArray2D<double>&, double, double)':
> > LinearAlgebra.cpp:(.text+0xf6): undefined reference to `dgemm_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DGESV(DataArray2D<double>&, DataArray1D<double>&,
> > DataArray1D<int>&)':
> > LinearAlgebra.cpp:(.text+0x1db): undefined reference to `dgesv_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DGESV(DataArray2D<double>&, DataArray2D<double>&,
> > DataArray1D<int>&)':
> > LinearAlgebra.cpp:(.text+0x2c8): undefined reference to `dgesv_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DGBSV(DataArray2D<double>&, DataArray1D<double>&,
> > DataArray1D<int>&, int, int)':
> > LinearAlgebra.cpp:(.text+0x3d7): undefined reference to `dgbsv_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DTPSV(char, char, char, int, DataArray1D<double>&,
> > DataArray1D<double>&)':
> > LinearAlgebra.cpp:(.text+0x472): undefined reference to `dtpsv_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DGETRF(DataArray2D<double>&, DataArray1D<int>&)':
> > LinearAlgebra.cpp:(.text+0x4e8): undefined reference to `dgetrf_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DGBTRF(DataArray2D<double>&, DataArray1D<int>&, int, int)':
> > LinearAlgebra.cpp:(.text+0x56e): undefined reference to `dgbtrf_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DGETRS(char, DataArray2D<double>&, DataArray1D<double>&,
> > DataArray1D<int>&)':
> > LinearAlgebra.cpp:(.text+0x615): undefined reference to `dgetrs_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DGBTRS(char, DataArray2D<double>&, DataArray1D<double>&,
> > DataArray1D<int>&, int, int)':
> > LinearAlgebra.cpp:(.text+0x6c9): undefined reference to `dgbtrs_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DGETRI(DataArray2D<double>&, DataArray1D<int>&,
> > DataArray1D<double>&)':
> > LinearAlgebra.cpp:(.text+0x755): undefined reference to `dgetri_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DTRTRI(char, char, DataArray2D<double>&)':
> > LinearAlgebra.cpp:(.text+0x88d): undefined reference to `dtrtri_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DGEQRF(DataArray2D<double>&, DataArray1D<double>&,
> > DataArray1D<double>&)':
> > LinearAlgebra.cpp:(.text+0x970): undefined reference to `dgeqrf_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::DORGQR(DataArray2D<double>&, DataArray1D<double>&,
> > DataArray1D<double>&)':
> > LinearAlgebra.cpp:(.text+0xa06): undefined reference to `dorgqr_'
> > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > `LAPACK::GeneralizedInverseSVD(DataArray2D<double>&,
> > DataArray2D<double>&)':
> > LinearAlgebra.cpp:(.text+0x189e): undefined reference to `dgesvd_'
> > ../../lib/libtempestbase.a(PolynomialInterp.o): In function
> > `PolynomialInterp::InterpolateCoeffs(int, double const_, double const_,
> > double_, double, double_, int*)':
> > PolynomialInterp.cpp:(.text+0xa9a): undefined reference to `dgesv_'
> > 
> > Most likely some missing packages on my end. I'll look for that. I'm
> > running Ubuntu locally so I can manage anything that is missing. Looks
> > like
> > my LAPACK set is incomplete. I ran "make clean" and then "make all" like
> > I
> > used to. Do I need a different compile sequence? Is there a configuration
> > file involved now? Thanks,
> > 
> > Jorge
> > 
> > On Fri, Feb 5, 2016 at 10:04 PM, Paul Ullrich notifications@github.com
> > wrote:
> > 
> > > Merged #3 https://github.com/paullric/tempestmodel/pull/3.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/paullric/tempestmodel/pull/3#event-541599844.
> > 
> > ## 
> > 
> > Jorge E. Guerra
> > PhD Candidate, Atmospheric Science, LAWR
> > Hoagland 230, U.C. Davis
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/paullric/tempestmodel/pull/3#issuecomment-180848497.

## 

Jorge E. Guerra
PhD Candidate, Atmospheric Science, LAWR
Hoagland 230, U.C. Davis

**Comment by ghost** [comment]
I figured out the problem. And this may apply to Agri as well: in the
Makefile for each of the test case directories, the LAPACK and BLAS flags
have to come after the object file argument for the compiler. I
moved $(LDFLAGS) so that the following is generated:

$(EXEC_TARGETS): %: $(BUILDDIR)/%.o $(TEMPESTLIBS)
$(CXX) -o $@ $(BUILDDIR)/$*.o $(LIBRARIES) $(LDFLAGS)

I'm able to compile but I am getting many of the following warnings:

In file included from /usr/lib/openmpi/include/mpi.h:253:0,
                 from ../../src/atm/Connectivity.h:30,
                 from ../../src/atm/GridPatch.h:27,
                 from ../../src/atm/Grid.h:20,
                 from ../../src/atm/Model.h:24,
                 from ../../src/atm/TempestInitialize.h:21,
                 from ../../src/atm/Tempest.h:20,
                 from
/home/jeguerra/Desktop/tempestmodel/test/shallowwater_sphere/RossbyHaurwitzWaveTest.cpp:17:
/usr/lib/openmpi/include/mpi_portable_platform.h:374:34: warning: invalid
suffix on literal; C++11 requires a space between literal and string macro
[-Wliteral-suffix]

_STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                  ^
/usr/lib/openmpi/include/mpi_portable_platform.h:374:63: warning: invalid
suffix on literal; C++11 requires a space between literal and string macro
[-Wliteral-suffix]

_STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)

I don't know what these mean of they're of any concern but they show up.
Thanks,

Jorge

On Sat, Feb 6, 2016 at 4:16 PM, Jorge Guerra jeguerra@ucdavis.edu wrote:

> Ok I see that things are very different now. Do I have to add to the
> system.make? It is not very clear to me how the new compile sequence
> executes. I have those libraries installed so the linking flags are there
> but the compiler can't find them.
> 
> On Sat, Feb 6, 2016 at 12:11 PM, Paul Ullrich notifications@github.com
> wrote:
> 
> > I suspect it's not detecting your system type and so is forgetting to
> > -lblas (or however you link with LAPACK). Try poking around in the mk
> > directory.
> > 
> > ~ Paul
> > 
> > > On Feb 6, 2016, at 11:59 AM, Jorge E Guerra notifications@github.com
> > > wrote:
> > > 
> > > Everyone,
> > > 
> > > I'm trying out the new code and my compilation breaks with the
> > > following:
> > > 
> > > mpiCC -L../../lib -L/opt/local/lib -llapack -lblas -o
> > > BaroclinicWaveJWTest
> > > 
> > > /home/jeguerra/Desktop/tempestmodel/test/nonhydro_sphere/build/BaroclinicWaveJWTest.o
> > > -lhardcoreatm -ltempestbase -lnetcdf -lnetcdf_c++
> > > ../../lib/libhardcoreatm.a(JacobianFreeNewtonKrylov.o): In function
> > > `JacobianFreeNewtonKrylov::PerformJFNK_NewtonStep(double*, int,
> > > double)':
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x18c8): undefined reference to
> > > `dnrm2_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x1a22): undefined reference to
> > > `dscal_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x1a6c): undefined reference to
> > > `dcopy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x1bb3): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x1d72): undefined reference to
> > > `ddot_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x1dfd): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x1e38): undefined reference to
> > > `dnrm2_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x1e8d): undefined reference to
> > > `dscal_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x1efa): undefined reference to
> > > `dcopy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x2176): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x21fa): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x2329): undefined reference to
> > > `dnrm2_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x2568): undefined reference to
> > > `daxpy_'
> > > ../../lib/libhardcoreatm.a(JacobianFreeNewtonKrylov.o): In function
> > > `JacobianFreeNewtonKrylov::PerformBICGSTAB_NewtonStep(double*, int,
> > > double)':
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x36e2): undefined reference to
> > > `dcopy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3789): undefined reference to
> > > `ddot_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3813): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3854): undefined reference to
> > > `dscal_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x38ab): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3913): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3a77): undefined reference to
> > > `ddot_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3b69): undefined reference to
> > > `dcopy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3bc6): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3c2e): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3d81): undefined reference to
> > > `ddot_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3dfc): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3e59): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3f3b): undefined reference to
> > > `dcopy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3f9d): undefined reference to
> > > `daxpy_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x3fe3): undefined reference to
> > > `ddot_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x40ef): undefined reference to
> > > `ddot_'
> > > JacobianFreeNewtonKrylov.cpp:(.text+0x441f): undefined reference to
> > > `dcopy_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DGEMM(DataArray2D<double>&, DataArray2D<double>&,
> > > DataArray2D<double>&, double, double)':
> > > LinearAlgebra.cpp:(.text+0xf6): undefined reference to `dgemm_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DGESV(DataArray2D<double>&, DataArray1D<double>&,
> > > DataArray1D<int>&)':
> > > LinearAlgebra.cpp:(.text+0x1db): undefined reference to `dgesv_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DGESV(DataArray2D<double>&, DataArray2D<double>&,
> > > DataArray1D<int>&)':
> > > LinearAlgebra.cpp:(.text+0x2c8): undefined reference to `dgesv_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DGBSV(DataArray2D<double>&, DataArray1D<double>&,
> > > DataArray1D<int>&, int, int)':
> > > LinearAlgebra.cpp:(.text+0x3d7): undefined reference to `dgbsv_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DTPSV(char, char, char, int, DataArray1D<double>&,
> > > DataArray1D<double>&)':
> > > LinearAlgebra.cpp:(.text+0x472): undefined reference to `dtpsv_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DGETRF(DataArray2D<double>&, DataArray1D<int>&)':
> > > LinearAlgebra.cpp:(.text+0x4e8): undefined reference to `dgetrf_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DGBTRF(DataArray2D<double>&, DataArray1D<int>&, int, int)':
> > > LinearAlgebra.cpp:(.text+0x56e): undefined reference to `dgbtrf_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DGETRS(char, DataArray2D<double>&, DataArray1D<double>&,
> > > DataArray1D<int>&)':
> > > LinearAlgebra.cpp:(.text+0x615): undefined reference to `dgetrs_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DGBTRS(char, DataArray2D<double>&, DataArray1D<double>&,
> > > DataArray1D<int>&, int, int)':
> > > LinearAlgebra.cpp:(.text+0x6c9): undefined reference to `dgbtrs_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DGETRI(DataArray2D<double>&, DataArray1D<int>&,
> > > DataArray1D<double>&)':
> > > LinearAlgebra.cpp:(.text+0x755): undefined reference to `dgetri_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DTRTRI(char, char, DataArray2D<double>&)':
> > > LinearAlgebra.cpp:(.text+0x88d): undefined reference to `dtrtri_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DGEQRF(DataArray2D<double>&, DataArray1D<double>&,
> > > DataArray1D<double>&)':
> > > LinearAlgebra.cpp:(.text+0x970): undefined reference to `dgeqrf_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::DORGQR(DataArray2D<double>&, DataArray1D<double>&,
> > > DataArray1D<double>&)':
> > > LinearAlgebra.cpp:(.text+0xa06): undefined reference to `dorgqr_'
> > > ../../lib/libtempestbase.a(LinearAlgebra.o): In function
> > > `LAPACK::GeneralizedInverseSVD(DataArray2D<double>&,
> > > DataArray2D<double>&)':
> > > LinearAlgebra.cpp:(.text+0x189e): undefined reference to `dgesvd_'
> > > ../../lib/libtempestbase.a(PolynomialInterp.o): In function
> > > `PolynomialInterp::InterpolateCoeffs(int, double const_, double const_,
> > > double_, double, double_, int*)':
> > > PolynomialInterp.cpp:(.text+0xa9a): undefined reference to `dgesv_'
> > > 
> > > Most likely some missing packages on my end. I'll look for that. I'm
> > > running Ubuntu locally so I can manage anything that is missing. Looks
> > > like
> > > my LAPACK set is incomplete. I ran "make clean" and then "make all"
> > > like I
> > > used to. Do I need a different compile sequence? Is there a
> > > configuration
> > > file involved now? Thanks,
> > > 
> > > Jorge
> > > 
> > > On Fri, Feb 5, 2016 at 10:04 PM, Paul Ullrich <notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > Merged #3 https://github.com/paullric/tempestmodel/pull/3.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/paullric/tempestmodel/pull/3#event-541599844.
> > > 
> > > ## 
> > > 
> > > Jorge E. Guerra
> > > PhD Candidate, Atmospheric Science, LAWR
> > > Hoagland 230, U.C. Davis
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/paullric/tempestmodel/pull/3#issuecomment-180848497.
> 
> ## 
> 
> Jorge E. Guerra
> PhD Candidate, Atmospheric Science, LAWR
> Hoagland 230, U.C. Davis

## 

Jorge E. Guerra
PhD Candidate, Atmospheric Science, LAWR
Hoagland 230, U.C. Davis

**Pull request merged**
